version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: home_library
    environment:
      POSTGRES_USER: ${USERNAME}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DATABASE}
    ports:
      - "${PORT_DB}:${PORT_DB}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${USERNAME} -d ${DATABASE}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app_service:
    image: taftoos/service-part1
    container_name: rest_app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      - ./.env:/usr/app/.env:ro
      - ./src:/usr/app/src:rw

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: