services:
  postgres:
    image: postgres:16-alpine
    container_name: home_library
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${USER_NAME}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DATABASE}
    ports:
      - '${PORT_DB}:${PORT_DB}'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${USER_NAME} -d ${DATABASE}']
      interval: ${HEALTH_INTERVAL}
      timeout: ${HEALTH_TIMEOUT}
      retries: ${HEALTH_RETRIES}

  app_service:
    image: taftoos/service-part3
    container_name: rest_app
    restart: always
    env_file:
      - .env
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      - ./.env:/usr/app/.env:ro
      - ./src:/usr/app/src:ro
      - ./test:/usr/app/test:ro
      - ./doc:/usr/app/doc:ro
      - /usr/app/node_modules

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
